### ISSUE TITLE
Filipino Localization 

### ISSUE THREAD

**Issue by cordeta** [Betoken/Whitepaper#4]
Good Day ! 

I would like to offer Tagalog Localization in your whitepaper 
The filename would be Betokenwhitepaper-tl-ph.md

Permit me to make pull requests in batches [minimum of 1000 words per PR]  as my translations will be reviewed by my adviser

Hoping for your response ,

Cheers !

**Comment by ZeframLou** [comment]
@cordeta Thanks for your help!

**Comment by cordeta** [comment]
@ZeframLou  Let me know if you some files besides your whitepaper that you want to be localized 

Cheers !

**Comment by cordeta** [comment]
i'll just send some PR's in the coming days . Thanks @ZeframLou
