### ISSUE TITLE
Betokenwhitepaper-tl.md creation

### ISSUE THREAD

**Issue by cordeta** [Betoken/Whitepaper#5]
Hi 
I Just want to tell you that we already created a staging file which will be used by my team . Will be translating this in a short while. I will send PR's right away once we finish some of the documents 
Thank you for the trust

Cheers !

**Comment by cordeta** [comment]
@ZeframLou   Hi , a response from you is highly appreciated .

**Comment by ZeframLou** [comment]
@cordeta Got it. We're really grateful for your work!
